- - delete_this_value_if_you_want_delete_config
  - false
- - config
  - token_bot: MTAyMzY0OTY2MTg4NzcyNTU2OA.GlrUnY.JFGMU74V8naKnjediIAtWW0axV4oNzF4SJbMuo
    owernid: "1013178486862643242"
    status_bot: VALORANT AR ON TOP
    status_type: PLAYING
