- - delete_this_value_if_you_want_delete_config
  - false
- - config
  - token_bot: ODY1Nzc4OTc4ODU3ODEyMDE5.GFnf8a.c-IZWDM9rNehY83CwifS22f020zL3FufCgUaGo
    owernid: "661255768070422538"
    status_bot: VALORANT AR ON TOP
    status_type: PLAYING
